### ISSUE TITLE
RPC14/OSA: Keepalived check scripts not working when >1s response time LP#1672857

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#2037]
###### Please provide the output to 'git describe --all' for  all deployments where you have confirmed it occurs.

All OSA versions using ansible-keepalived role

##### What type of issue is this? Please tick the appropriate box.
- [x] bug - existing functionality that does not work for you as documented
- [ ] feature - new functionality that you would like to see added

##### What is the expected behavior?

Keepalived works when using 2 ICMP packets for ping

##### What is actually happening?

See https://bugs.launchpad.net/openstack-ansible/+bug/1672857

##### What were you attempting to do when you encountered this error (give as much detail as possible)? 

Testing a more mature config like:
```
keepalived_scripts:
  haproxy_check_script:
    check_script: "killall -0 haproxy"
    timeout: 2
  pingable_check_script:
    check_script: "/bin/ping -c {{ keepalived_ping_count }} {{ keepalived_ping_address }} 1>&2"
    interval: "{{ keepalived_ping_interval }}"
    fall: 2
    rise: 4
    timeout: 5
```

and I noticed the role does not support timeouts attributes nor are the values correctly set

##### How can we reproduce this issue?

See above

##### How can we verify your issue is addressed?

Fix already in progress

##### If you are using or know of a workaround please describe the necessary steps?

None

##### What is your evaluation on the importance of this issue, and why?

Prio 2

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [ ] master
- [ ] newton-14.0
- [ ] mitaka-13.1

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [ ] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [ ] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):
